# spring:
#   application:
#     name: app-monitor
#   cloud:
#       config:
#         uri: http://${configurl}:777/
#         profile: ${profile}
#         label: master

#--configurl=172.20.67.102 --profile=dev