spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  datasource:
    name: zipkin
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    schema[0]: classpath:/mysql.sql #数据库脚本创建地址，当有多个是可使用[x]表示集合第几个元素
    initialize: true
    continue-on-error: true

server:
  port: 9411
  address: 127.0.0.2

zipkin:
  storage:
#     mysql:
#       host: 127.0.0.1
#       port: 3306
#       username: root
#       password: root
#       db: zipkin
    type: mysql #保存数据到mysql